package com.example.anilist.pojo

data class Anime(
    val aired: Aired,
    val airing: Boolean,
    val broadcast: Broadcast,
    val duration: String,
    val episodes: Int,
    val licensors: List<Any>,
    val producers: List<Producer>,
    val rating: String,
    val season: String,
    val source: String,
    val studios: List<Studio>,
    val trailer: Trailer,
    val type: String,
    val year: Int,

    val mal_id: Int,
    val url: String,
    val images: Images,
    val approved: Boolean,
    val title: String,
    val title_english: String,
    val title_japanese: String,
    val title_synonyms: List<String>,
    val titles: List<Title>,
    val status: String,
    val score: Double,
    val scored_by: Int,
    val rank: Int,
    val popularity: Int,
    val members: Int,
    val synopsis: String?,
    val favorites: Int,
    val background: Any,
    val genres: List<Genre>,
    val explicit_genres: List<Any>,
    val themes: List<Theme>,
    val demographics: List<Any>,

    )