package com.example.anilist.pojo

data class MangaX(
    val mal_id: Int,
    val url: String,
    val images: Images,
    val approved: Boolean,
    val title: String,
    val title_english: String,
    val title_japanese: String,
    val title_synonyms: List<String>,
    val titles: List<Title>,
    val type: String,
    val chapters: Int,
    val volumes: Int,
    val status: String,
    val publishing: Boolean,
    val published: Aired,
    val score: Double,
    val scored_by: Int,
    val rank: Int,
    val popularity: Int,
    val members: Int,
    val favorites: Int,
    val synopsis: String?,
    val background: Any,
    val authors: List<Entry>,
    val serializations: List<Entry>,
    val genres: List<Genre>,
    val explicit_genres: List<Genre>,
    val themes: List<Theme>,
    val demographics: List<Entry>,
    val relations: List<Relation>,
    val `external`: List<External>,
)
